### ISSUE TITLE
Black Screen (cyclic reboot)

### ISSUE THREAD

**Issue by alexxxdev** [fbiego/esp32-c3-mini#10]
hi, i'm trying to build and install the latest firmware for ESP32-C3, and I get a cyclic reboot

Rebooting...
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40381f8c
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5810,len:0x438
load:0x403cc710,len:0x90c
load:0x403ce710,len:0x2624
entry 0x403cc710
Guru Meditation Error: Core  0 panic'ed (Illegal instruction). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x420a2b5a  RA      : 0x420a2b10  SP      : 0x3fcddd40  GP      : 0x3fc92200
TP      : 0x00000000  T0      : 0x4005890e  T1      : 0x4038b42e  T2      : 0x52583f01
S0/FP   : 0x0000004f  S1      : 0x3fcbd454  A0      : 0x00000001  A1      : 0xffffffff
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000004  A5      : 0x3c268000
A6      : 0xefffffff  A7      : 0x03ffffff  S2      : 0x3c279938  S3      : 0x3fcb88cc
S4      : 0x3fcbd454  S5      : 0x3fcde188  S6      : 0x42000020  S7      : 0x3c0c0020
S8      : 0x00010020  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0xffff0000  T4      : 0x706d7564  T5      : 0x1bf7ecb0  T6      : 0x00000000
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000002  MTVAL   : 0x7487b787
MHARTID : 0x00000000

Stack memory:
3fcddd40: 0xc22657dc 0x84aec606 0x842a4581 0xe1219782 0x8522405c 0x4bfc43d8 0x9782430c 0x4008e90d
3fcddd60: 0x411c85a6 0x97824bdc 0x85224c5c 0x00000001 0x405ccc5c 0x4bfc43d8 0x9782470c 0x3c26866c
3fcddd80: 0x00f50c63 0x442240b2 0x01414492 0x07938082 0x19e31060 0xb7e1fef5 0x8522405c 0x40b24422
3fcddda0: 0xa3034492 0x458502c7 0x83020141 0x1101415c 0x43d8ca26 0x4bfc84ae 0xcc22430c 0xc632ce06
3fcdddc0: 0x842ac436 0x46a29782 0xc5094632 0x10600793 0x02f51f63 0x85a64008 0x539c411c 0x3fcde294
3fcddde0: 0xe7938522 0xcc5c0017 0x43d8405c 0x4b0c4bfc 0x07939782 0x1c631060 0x405c00f5 0x44628522
3fcdde00: 0x44d240f2 0x02c7a303 0x61054585 0x40f28302 0x44d24462 0x80826105 0x1101415c 0x43d8ca26
3fcdde20: 0x4bfc84ae 0xcc22430c 0x842ace06 0xc5099782 0x10600793 0x00f51763 0x85a64008 0x4fdc411c
3fcdde40: 0x405c9782 0x00f10593 0x579c8522 0xe5199782 0x00f14783 0x00978463 0x10500513 0x446240f2
3fcdde60: 0x610544d2 0x41088082 0x411c85b2 0x0187a303 0x71798302 0xd226d422 0xd606ce4e 0xcc52d04a
3fcdde80: 0xc85aca56 0x84aa57fd 0x440189ae 0x00f58363 0x0405842e 0x4ad14a05 0x40885b7d 0x5f9c411c
3fcddea0: 0xc51d9782 0x007040dc 0x53fc4585 0x97828526 0x47b2e929 0x0017f513 0x4cd8e50d 0x00177693
3fcddec0: 0xffffffff 0x8b89ccd8 0x0513cf8d 0xa8151060 0xfd4405e3 0x44c8449c 0x47dc4585 0x9782147d
3fcddee0: 0x8922bf6d 0x008af363 0x449c4951 0x85ca44c8 0x978247dc 0xfb6983e3 0x41240433 0x0513fc59
3fcddf00: 0x50b21070 0x54925422 0x49f25902 0x4ad24a62 0x61454b42 0x49188082 0x89854689 0x01071793
3fcddf20: 0x856383c1 0xe9630ad7 0xc7e500f6 0x81634685 0x65190cd7 0x8082050d 0x8a634691 0xe06302d7
3fcddf40: 0x469506d7 0xfed797e3 0x8b894d5c 0x37b7cf81 0xa7833fc9 0xc683cd87 0x00000000 0x00000000
3fcddf60: 0x00000000 0x00c937b7 0xcd47a783 0x4d5cb7ed 0xc38d8b89 0x3fc937b7 0xcd87a783 0x0027c683
3fcddf80: 0x0593c1e1 0x061306c0 0x00000000 0x00000000 0x00000000 0x00c937b7 0x00000000 0x00000000
3fcddfa0: 0x00000000 0x00c937b7 0x00000000 0x00000000 0x00000000 0x00130bc0 0x00000000 0x00000000
3fcddfc0: 0x00000000 0x00833fc9 0x00000000 0x00000000 0x00000000 0x00833fc9 0x00000000 0x00000000
3fcddfe0: 0x00000000 0x00b7b74d 0x00000000 0x00000000 0x00000000 0x00b7cb91 0x00000000 0x00000000
3fcde000: 0x00000000 0x004145b1 0x00000000 0x00000000 0x00000000 0x00918b89 0x3fc937b7 0x00001388
3fcde020: 0x0057c683 0x45cdc59d 0x00001388 0xa7833fc9 0xb7fdcd47 0x00001388 0x0593bfbd 0xb70d0bb0
3fcde040: 0x06b00593 0xb7914661 0x03b00593 0x45adbfe5 0x458dbfd5 0x5503bfc5 0x150101a5 0x00153513
3fcde060: 0x00456513 0x71198082 0x99b7d6ce 0xa7833fcb 0xcce24809 0xc6bedca2 0xdaa6415c 0xac03d4d2
3fcde080: 0x5fbc04c7 0xd0dad2d6 0xd8cade86 0xcae6cede 0x45818b2e 0x84328aaa 0x978284b6 0xc0380000
3fcde0a0: 0x00000000 0x3fcbb000 0xc0380000 0x00000018 0x3fcbb320 0x00000000 0x3fcbb320 0x4038fe98
3fcde0c0: 0xe0974505 0x80e701ce 0x47367000 0xbaad5678 0x0c638552 0x3fc92c30 0x00000000 0x3fcb9000
3fcde0e0: 0x003f0004 0x00000000 0x60002000 0x4038dfc2 0x00000000 0x00000000 0x3fcde11c 0x00000004
3fcde100: 0x00000000 0x3fc92c30 0x00000000 0x3fcb9000 0x003f0424 0x00000000 0x60002000 0x4038dfc2
3fcde120: 0xffffffff 0xffffffff 0x3fcde14c 0x00000004 0xffffffff 0xffffffff 0x003f0424 0x40391058

ELF file SHA256: 4aeee748fae3616f

**Comment by fbiego** [comment]
try to disable custom watchface by commentting the line as shown
https://github.com/fbiego/esp32-c3-mini/blob/dfc427e60226e6ef6abf7929c7cf4630f28fddca/platformio.ini#L139

**Comment by alexxxdev** [comment]
> try to disable custom watchface by commentting the line as shown
> 
> https://github.com/fbiego/esp32-c3-mini/blob/dfc427e60226e6ef6abf7929c7cf4630f28fddca/platformio.ini#L139

doesn't work(  (for ESP32-C3 it is line 188)

**Comment by fbiego** [comment]
I just tested on ESP32 C3 Mini board and it works fine.

**Comment by alexxxdev** [comment]
Due to the board revision I had to change the configuration a little:

```
platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.05.00/platform-espressif32.zip
board = esp32-c3-devkitm-1
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
build_flags =   
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
```

after that everything works as it should

**Comment by alexxxdev** [comment]
Due to the board revision I had to change the configuration a little:

```
platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.05.00/platform-espressif32.zip
board = esp32-c3-devkitm-1
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
build_flags =   
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
```
after that everything works as it should
