### ISSUE TITLE
Reset when notification received

### ISSUE THREAD

**Issue by Santix29** [fbiego/esp32-c3-mini#3]
I have an esp32-s3 here, I changed the pins and it's working, but when a notification arrives, it seems to reset and lose the connection with the phone. I attach a video demonstration (sorry for the bad quality)

https://github.com/fbiego/esp32-c3-mini/assets/104246135/ffd77673-8606-4ae7-8b07-dac670692eec

**Comment by fbiego** [comment]
can you share the serial monitor logs? Also note that it is not possible to upload a watchface from the app. It needs to be built with the code
