### ISSUE TITLE
Sharing of you ESP32 C3 mini LCD project

### ISSUE THREAD

**Issue by aeonSolutions** [fbiego/esp32-c3-mini#4]
hi @fbiego ,
great project!

I'm sharing it on my own catalog of ESP32 projects here on GitHub. Here's the link:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md) 

![image](https://github.com/fbiego/esp32-c3-mini/assets/7936768/861e8cab-4da9-40e3-a223-860ee7c3e7cb)

**Comment by fbiego** [comment]
That's awesome, thanks
